// 디자인 지식 그래프의 단일 진실 공급원.
// 모든 개념·분석 노드와 그 관계(relatedConcepts, demonstrates)를 등록한다.
import type {
  AnalysisNode,
  ConceptNode,
  GlobalReference,
  PatternNode,
} from "@/lib/types";

export const concepts: ConceptNode[] = [
  {
    type: "concept",
    slug: "design-system",
    title: "디자인 시스템이란",
    titleEn: "What is a Design System",
    category: "system",
    summary:
      "스타일 가이드도, 단순 UI 키트도 아니다. 원칙·토큰·컴포넌트·패턴·가이드라인이 쌓인 살아있는 계층 구조.",
    difficulty: "intro",
    readingMinutes: 6,
    relatedConcepts: ["design-tokens", "components", "patterns-guidelines"],
  },
  {
    type: "concept",
    slug: "design-tokens",
    title: "디자인 토큰",
    titleEn: "Design Tokens",
    category: "system",
    summary:
      "색·간격·반경 같은 디자인 결정을 이름 붙은 변수로 저장한 것. 디자인과 코드를 잇는 가장 작은 단위.",
    difficulty: "core",
    readingMinutes: 7,
    relatedConcepts: ["design-system", "color", "spacing", "theming"],
  },
  {
    type: "concept",
    slug: "color",
    title: "색채",
    titleEn: "Color",
    category: "color",
    summary:
      "브랜드 색, 의미를 가진 색(semantic), 명도 단계. 색은 장식이 아니라 정보의 위계를 만든다.",
    difficulty: "intro",
    readingMinutes: 7,
    relatedConcepts: ["design-tokens", "visual-hierarchy", "accessibility"],
  },
  {
    type: "concept",
    slug: "typography",
    title: "타이포그래피",
    titleEn: "Typography",
    category: "typography",
    summary:
      "타입 스케일, 위계, 한국어 본문의 가독성. 화면의 90%는 글자다.",
    difficulty: "intro",
    readingMinutes: 7,
    relatedConcepts: ["visual-hierarchy", "spacing", "design-tokens", "content-design"],
  },
  {
    type: "concept",
    slug: "spacing",
    title: "여백과 간격",
    titleEn: "Spacing",
    category: "layout",
    summary:
      "8pt 같은 간격 스케일. 여백은 빈 공간이 아니라 요소를 묶고 가르는 도구다.",
    difficulty: "intro",
    readingMinutes: 6,
    relatedConcepts: ["layout-grid", "design-tokens", "visual-hierarchy"],
  },
  {
    type: "concept",
    slug: "layout-grid",
    title: "레이아웃과 그리드",
    titleEn: "Layout & Grid",
    category: "layout",
    summary:
      "그리드·정렬·반응형. 화면을 예측 가능한 골격 위에 올리는 법.",
    difficulty: "core",
    readingMinutes: 7,
    relatedConcepts: ["spacing", "visual-hierarchy", "components", "responsive-design"],
  },
  {
    type: "concept",
    slug: "visual-hierarchy",
    title: "시각적 위계",
    titleEn: "Visual Hierarchy",
    category: "foundation",
    summary:
      "크기·색·여백·대비로 '먼저 볼 것'을 정하는 일. 모든 디자인 결정의 목적지.",
    difficulty: "intro",
    readingMinutes: 6,
    relatedConcepts: ["color", "typography", "spacing", "motion"],
  },
  {
    type: "concept",
    slug: "components",
    title: "컴포넌트",
    titleEn: "Components",
    category: "system",
    summary:
      "버튼·입력창처럼 재사용하는 UI 조각. 상태(state)와 변형(variant)으로 설계한다.",
    difficulty: "core",
    readingMinutes: 7,
    relatedConcepts: ["design-system", "patterns-guidelines", "layout-grid", "states"],
  },
  {
    type: "concept",
    slug: "patterns-guidelines",
    title: "패턴과 가이드라인",
    titleEn: "Patterns & Guidelines",
    category: "system",
    summary:
      "컴포넌트를 언제·어떻게 조합하는지에 대한 합의. 시스템이 '판단'을 담는 층.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["components", "design-system", "accessibility"],
  },
  {
    type: "concept",
    slug: "accessibility",
    title: "접근성",
    titleEn: "Accessibility",
    category: "accessibility",
    summary:
      "명도 대비, 키보드, 스크린리더, 터치 타깃. 모두가 쓸 수 있어야 좋은 디자인이다.",
    difficulty: "core",
    readingMinutes: 7,
    relatedConcepts: ["color", "patterns-guidelines", "visual-hierarchy", "states"],
  },

  // ── 행동·인터랙션 ──
  {
    type: "concept",
    slug: "motion",
    title: "모션",
    titleEn: "Motion",
    category: "behavior",
    summary:
      "장식이 아니라 기능. 좋은 모션은 시선을 안내하고, 변화의 인과를 설명하고, 화면 사이를 부드럽게 잇는다.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["visual-hierarchy", "components", "accessibility"],
  },
  {
    type: "concept",
    slug: "affordance",
    title: "어포던스",
    titleEn: "Affordance",
    category: "behavior",
    summary:
      "이걸 누를 수 있다, 끌 수 있다, 입력할 수 있다 — 모양만으로 사용법을 알리는 신호.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["components", "visual-hierarchy", "accessibility"],
  },
  {
    type: "concept",
    slug: "interaction-feedback",
    title: "인터랙션 피드백",
    titleEn: "Interaction Feedback",
    category: "behavior",
    summary:
      "사용자가 한 행동에 시스템이 즉시 응답한다는 신호. 누른 듯한 눌림, 저장된 듯한 표시.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["motion", "states", "accessibility"],
  },
  {
    type: "concept",
    slug: "states",
    title: "UI 상태",
    titleEn: "UI States",
    category: "behavior",
    summary:
      "기본·호버·포커스·눌림·비활성·로딩·오류. 한 컴포넌트의 일생을 모두 설계해야 화면이 깨지지 않는다.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["components", "accessibility", "visual-hierarchy"],
  },

  // ── 정보구조·콘텐츠 ──
  {
    type: "concept",
    slug: "information-architecture",
    title: "정보구조",
    titleEn: "Information Architecture",
    category: "content",
    summary:
      "무엇을 어디에 둘 것인가. 메뉴·페이지·라벨의 골격을 정해 사용자가 길을 잃지 않게 한다.",
    difficulty: "core",
    readingMinutes: 7,
    relatedConcepts: ["visual-hierarchy", "layout-grid"],
  },
  {
    type: "concept",
    slug: "content-design",
    title: "콘텐츠 디자인",
    titleEn: "Content Design",
    category: "content",
    summary:
      "화면의 글을 디자인 결정으로 다루는 일. 문장의 길이·순서·톤이 곧 화면의 구조다.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["typography", "microcopy", "visual-hierarchy"],
  },
  {
    type: "concept",
    slug: "iconography",
    title: "아이콘그래피",
    titleEn: "Iconography",
    category: "content",
    summary:
      "아이콘은 그림이 아니라 약자다. 일관된 기하·획·여백의 규칙 위에서만 작동한다.",
    difficulty: "core",
    readingMinutes: 5,
    relatedConcepts: ["components", "visual-hierarchy", "accessibility"],
  },
  {
    type: "concept",
    slug: "microcopy",
    title: "마이크로카피",
    titleEn: "Microcopy",
    category: "content",
    summary:
      "버튼 라벨, 빈 상태 문구, 오류 메시지. 가장 작은 글이 가장 자주 읽히고 가장 자주 망친다.",
    difficulty: "core",
    readingMinutes: 5,
    relatedConcepts: ["content-design", "typography", "accessibility"],
  },

  // ── 기술·구현 ──
  {
    type: "concept",
    slug: "responsive-design",
    title: "반응형 디자인",
    titleEn: "Responsive Design",
    category: "engineering",
    summary:
      "한 화면이 여러 너비에서 살아남는 법. 브레이크포인트·유체 그리드·콘텐츠 우선순위의 합.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["layout-grid", "spacing", "typography"],
  },
  {
    type: "concept",
    slug: "theming",
    title: "테마와 다크모드",
    titleEn: "Theming",
    category: "engineering",
    summary:
      "같은 시스템을 라이트·다크·브랜드별로 갈아끼우는 법. 토큰이 그 시작이자 끝이다.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["design-tokens", "color", "accessibility"],
  },
  {
    type: "concept",
    slug: "performance",
    title: "성능과 인지된 속도",
    titleEn: "Performance",
    category: "engineering",
    summary:
      "실제 빠르기와 빠르게 느껴지기는 다른 디자인 문제다. 스켈레톤·낙관적 업데이트·모션이 후자의 도구다.",
    difficulty: "advanced",
    readingMinutes: 6,
    relatedConcepts: ["motion", "visual-hierarchy"],
  },
];

export const patterns: PatternNode[] = [
  {
    type: "pattern",
    slug: "empty-state",
    title: "빈 상태",
    titleEn: "Empty State",
    category: "feedback",
    summary:
      "보여줄 데이터가 없을 때의 화면. 빈 화면은 실수가 아니라 설계할 대상이다.",
    problem: "데이터가 아직 없을 때, 화면을 어떻게 채워 다음 행동으로 이끌 것인가.",
    difficulty: "core",
    readingMinutes: 5,
    relatedConcepts: ["visual-hierarchy", "typography", "microcopy"],
    relatedPatterns: ["data-table"],
  },
  {
    type: "pattern",
    slug: "form-validation",
    title: "폼 검증",
    titleEn: "Form Validation",
    category: "input",
    summary:
      "입력 오류를 언제·어디서·어떤 톤으로 알릴지에 대한 합의. 검증은 비난이 아니라 안내다.",
    problem: "사용자 입력의 오류를 언제·어떻게 알려 좌절 없이 고치게 할 것인가.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["accessibility", "color", "visual-hierarchy", "microcopy"],
    relatedPatterns: ["modal-dialog"],
  },
  {
    type: "pattern",
    slug: "modal-dialog",
    title: "모달 다이얼로그",
    titleEn: "Modal Dialog",
    category: "disclosure",
    summary:
      "흐름을 멈추고 한 가지 결정에 집중시키는 겹화면. 강력한 만큼 아껴 써야 한다.",
    problem: "다른 모든 것을 멈추고 한 가지에 집중시켜야 할 때 무엇을 지킬 것인가.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["components", "accessibility", "layout-grid", "motion", "states"],
    relatedPatterns: ["form-validation"],
  },
  {
    type: "pattern",
    slug: "card-grid",
    title: "카드 그리드",
    titleEn: "Card Grid",
    category: "layout",
    summary:
      "비슷한 항목을 카드로 묶어 격자에 배열하는 법. 훑어보기와 비교를 돕는다.",
    problem: "성격이 비슷한 항목 여러 개를 한눈에 훑어보게 하려면 어떻게 배열할까.",
    difficulty: "core",
    readingMinutes: 5,
    relatedConcepts: ["layout-grid", "spacing", "components", "responsive-design"],
    relatedPatterns: ["data-table"],
  },
  {
    type: "pattern",
    slug: "data-table",
    title: "데이터 테이블",
    titleEn: "Data Table",
    category: "layout",
    summary:
      "행과 열로 된 많은 데이터를 읽고 비교하게 하는 법. 정렬·밀도·정렬축이 핵심.",
    problem: "행과 열로 된 많은 데이터를 빠르게 읽고 비교하게 하려면 무엇을 정할까.",
    difficulty: "core",
    readingMinutes: 6,
    relatedConcepts: ["typography", "spacing", "visual-hierarchy", "responsive-design"],
    relatedPatterns: ["card-grid", "empty-state"],
  },
  {
    type: "pattern",
    slug: "navigation-bar",
    title: "내비게이션 바",
    titleEn: "Navigation Bar",
    category: "navigation",
    summary:
      "사용자가 지금 어디에 있고 어디로 갈 수 있는지 보여주는 골격. 모든 화면의 닻.",
    problem: "사용자가 현재 위치와 갈 수 있는 곳을 늘 알게 하려면 무엇을 보여줄까.",
    difficulty: "core",
    readingMinutes: 5,
    relatedConcepts: ["components", "visual-hierarchy", "layout-grid", "information-architecture"],
    relatedPatterns: [],
  },
];

export const analyses: AnalysisNode[] = [
  {
    type: "analysis",
    slug: "toss",
    title: "토스 — Apps in Toss",
    org: "비바리퍼블리카 (Toss)",
    industry: "fintech",
    delivery: "docs-site",
    summary:
      "토스 슈퍼앱 안에서 외부 개발자가 미니앱을 만들도록 제공하는 플랫폼 SDK형 디자인 시스템.",
    url: "https://developers-apps-in-toss.toss.im/design/components.html",
    demonstrates: ["design-system", "components", "spacing", "visual-hierarchy"],
    designMd: "toss.design.md",
    brandColor: "#3182F6",
    takeaway: "극단적 단순함은 기능이다 — 덜어내서 빠르게.",
  },
  {
    type: "analysis",
    slug: "krds",
    title: "KRDS — 디지털 정부 디자인 시스템",
    org: "행정안전부",
    industry: "public",
    delivery: "docs-site",
    summary:
      "대한민국 정부 공공서비스의 표준 디자인 시스템. 접근성과 거버넌스가 1급 요구사항.",
    url: "https://www.krds.go.kr/html/site/index.html",
    demonstrates: ["design-system", "accessibility", "patterns-guidelines", "color"],
    designMd: "krds.design.md",
    brandColor: "#256EF4",
    takeaway: "접근성을 먼저 두면 시스템 전체가 단단해진다.",
  },
  {
    type: "analysis",
    slug: "gmarket",
    title: "GDS — G마켓 디자인 시스템",
    org: "지마켓 (신세계/SSG)",
    industry: "ecommerce",
    delivery: "docs-site",
    summary:
      "대규모 이커머스의 상품 진열·전환·프로모션 UI를 표준화한 커머스형 디자인 시스템.",
    url: "https://gds.gmarket.co.kr/",
    demonstrates: ["design-system", "components", "color", "typography"],
    designMd: "gmarket.design.md",
    brandColor: "#329CFF",
    takeaway: "브랜드와 전환 목표가 시스템의 모든 결정에 새겨진다.",
  },
  {
    type: "analysis",
    slug: "wanted",
    title: "원티드 디자인 시스템",
    org: "원티드랩 (Wanted)",
    industry: "recruit",
    delivery: "figma",
    summary:
      "Figma Community 파일로 공개된 채용 플랫폼의 디자인 시스템. 디자인 툴이 곧 시스템.",
    url: "https://www.figma.com/community/file/wanted-design-system",
    demonstrates: ["design-system", "design-tokens", "components"],
    designMd: "wanted.design.md",
    brandColor: "#3366FF",
    takeaway: "Figma 파일 자체가 단일 진실 공급원이 될 수 있다.",
  },
  {
    type: "analysis",
    slug: "letters",
    title: "Letters — Patients, not Paperwork",
    org: "Letters",
    industry: "global",
    delivery: "docs-site",
    summary:
      "의료진의 행정 문서 부담을 AI로 줄여주는 제품의 마케팅 사이트. Framer로 만든 단색·부드러운 디자인.",
    url: "https://letters.app/",
    demonstrates: ["color", "typography", "visual-hierarchy", "spacing"],
    designMd: "letters.design.md",
    brandColor: "#2597D0",
    takeaway: "제품의 약속이 색·모서리·모션을 한 톤으로 묶는다.",
  },
];

/** 글로벌 보너스 — 위키·컬렉션에서 가벼운 참고로 노출. */
export const globalReferences: GlobalReference[] = [
  {
    name: "Material Design",
    org: "Google",
    url: "https://m3.material.io/",
    note: "토큰·컴포넌트·모션까지 가장 방대한 공개 시스템. 디자인 시스템의 사실상 교과서.",
  },
  {
    name: "Human Interface Guidelines",
    org: "Apple",
    url: "https://developer.apple.com/design/human-interface-guidelines",
    note: "컴포넌트 명세보다 '원칙과 판단'을 가르치는 가이드라인 중심 시스템.",
  },
  {
    name: "Polaris",
    org: "Shopify",
    url: "https://polaris.shopify.com/",
    note: "상거래 관리자 화면을 위한 시스템. 콘텐츠(글쓰기) 가이드가 강하다.",
  },
  {
    name: "Carbon",
    org: "IBM",
    url: "https://carbondesignsystem.com/",
    note: "오픈소스 엔터프라이즈 시스템. 디자인 토큰 구조의 모범 사례.",
  },
];
